import fs from 'node:fs/promises';import path from 'node:path';import {Presentation,PresentationFile} from '@oai/artifact-tool';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const ROOT=path.resolve('.'),OUT=path.join(ROOT,'output/Supplementary_Fig4_materials'),D=JSON.parse(await fs.readFile(path.join(OUT,'data/plot_data.json'),'utf8'));
const W=1440,H=1840,scale=180/(15*25.4),P=Presentation.create({slideSize:{width:W*scale,height:H*scale}}),S=P.slides.add();S.background.fill='#FFFFFF';
const C={ink:'#000000',grid:'#E1E8EA',axis:'#34454D',teal:'#237F8D',gold:'#C69650',rose:'#B96883',low:'#458CAD',mid:'#D7A151',high:'#BE647E'};const states=[C.low,C.mid,C.high],mods=['Bile acid','Oxidative lipid','Aromatic AA / indole','SCFA / butyrate'],mc=[C.teal,'#B17950','#5A82AF','#6D9467'];let serial=0;
function txt(t,x,y,w,h=28,size=22,bold=false,align='left',rot=0){const s=S.shapes.add({geometry:'textbox',name:`text-${++serial}`,position:{left:x*scale,top:y*scale,width:w*scale,height:h*scale,rotation:rot},fill:'none',line:{fill:'none',width:0}});s.text=String(t);s.text.style={typeface:'Times New Roman',fontSize:size*scale,bold,color:'#000000',alignment:align,verticalAlignment:'middle',autoFit:'none',wrap:'none',insets:{left:0,right:0,top:0,bottom:0}};return s;}
function pathline(points,color=C.axis,width=1.5,fill='none',closed=false){let xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),x=Math.min(...xs),y=Math.min(...ys),w=Math.max(.1,Math.max(...xs)-x),h=Math.max(.1,Math.max(...ys)-y);let cmds=points.map((p,i)=>({[i?'lineTo':'moveTo']:{x:p[0]-x,y:p[1]-y}}));if(closed)cmds.push({close:{}});return S.shapes.add({geometry:'custom',name:`data-path-${++serial}`,position:{left:x*scale,top:y*scale,width:w*scale,height:h*scale},fill,line:{fill:color,width:width*scale},customPaths:[{width:w*scale,height:h*scale,commands:cmds.map(c=>c.close?c:Object.fromEntries(Object.entries(c).map(([k,v])=>[k,{x:v.x*scale,y:v.y*scale}])))}]});}
function ln(x,y,x2,y2,c=C.axis,w=1.5){return pathline([[x,y],[x2,y2]],c,w)}
function rect(x,y,w,h,fill,linecolor='none',lw=0){return S.shapes.add({geometry:'rect',name:`data-box-${++serial}`,position:{left:x*scale,top:y*scale,width:w*scale,height:h*scale},fill,line:{fill:linecolor,width:lw*scale}})}
function point(x,y,c,size=8,open=false,shape='ellipse'){return S.shapes.add({geometry:shape,name:`data-point-${++serial}`,position:{left:(x-size/2)*scale,top:(y-size/2)*scale,width:size*scale,height:size*scale},fill:open?'#FFFFFF':c,line:{fill:c,width:open?1.7*scale:0}})}
function panel(l,t,x,y,w){txt(l,x,y,34,38,36,true);txt(t,x+42,y+1,w-43,34,25,true)}
function axes({x,y,w,h,xmin=0,xmax=1,ymin=0,ymax=1,xt=[0,.5,1],yt=[0,.5,1],xlabel='',ylabel='',tick=21,grid=true}){const X=v=>x+(v-xmin)*w/(xmax-xmin),Y=v=>y+h-(v-ymin)*h/(ymax-ymin);if(grid)for(let v of yt)ln(x,Y(v),x+w,Y(v),C.grid,1);ln(x,y,x,y+h);ln(x,y+h,x+w,y+h);for(let v of xt){ln(X(v),y+h,X(v),y+h+5);txt(String(v).replace('-','−'),X(v)-36,y+h+9,72,26,tick,false,'center')}for(let v of yt){ln(x-5,Y(v),x,Y(v));txt(String(v).replace('-','−'),x-56,Y(v)-13,45,26,tick,false,'right')}if(xlabel)txt(xlabel,x-6,y+h+44,w+12,28,22,false,'center');if(ylabel)txt(ylabel,x-160,y+h/2-15,150,30,22,false,'center',270);return{X,Y,x,y,w,h};}
function eh(a,v,ci,y,c){ln(a.X(ci[0]),y,a.X(ci[1]),y,c,2);for(let val of ci)ln(a.X(val),y-5,a.X(val),y+5,c,1.8);point(a.X(v),y,c)}
function ev(a,v,ci,x,c,open=false,shape='ellipse'){if(ci[0]!=null){ln(x,a.Y(ci[0]),x,a.Y(ci[1]),c,2);for(let q of ci)ln(x-5,a.Y(q),x+5,a.Y(q),c,1.7)}point(x,a.Y(v),c,9,open,shape)}
function legend(t,c,x,y,w=170,shape='ellipse'){point(x+7,y+13,c,8,false,shape);txt(t,x+21,y,w,27,21)}
const fmt=v=>v.toFixed(3),foldcols=['#2E7A9A','#329B97','#6582A8','#6B987B','#A8874B','#69727C'];
txt('Supplementary Figure S4',26,16,800,47,35,true);
txt('HI model tuning, calibration and forecast comparisons',26,65,1350,43,30,true);
txt('152 windows / 66 participants. Predictors use information available by t2',26,114,1350,35,25);
const top=178,dx=477,rowH=493;
function box(l,title,col,row){let x=24+col*dx,y=top+row*rowH;panel(l,title,x,y,446);return{x,y};}
let q=box('A','Training-only tuning',0,0);let a=axes({x:q.x+80,y:q.y+76,w:343,h:250,xmin:-3,xmax:3,ymin:.35,ymax:.7,xt:[-3,0,3],yt:[.4,.5,.6,.7],xlabel:'log10(alpha)',ylabel:'Inner-CV MAE',tick:24});
for(let f=0;f<6;f++){let vals=[];for(let ai=0;ai<13;ai++){let al=10**(-3+ai*.5),rr=D.sensitivity.filter(v=>v.family===f&&Math.abs(Math.log10(v.alpha)-Math.log10(al))<1e-8);vals.push([a.X(Math.log10(al)),a.Y(rr.reduce((s,v)=>s+v.mae,0)/rr.length)]);}pathline(vals,foldcols[f],2.8)}
['1 HI, no change','1 HI, prior change','1 HI, 3 dynamics','2 HI, no change','2 HI, prior change','2 HI, 3 dynamics'].forEach((t,i)=>{const xx=q.x+44+(i%2)*213,yy=q.y+416+Math.floor(i/2)*24;ln(xx,yy+10,xx+25,yy+10,foldcols[i],2.6);txt(t,xx+31,yy-3,182,24,20)});
q=box('B','Locked-model calibration',1,0);a=axes({x:q.x+81,y:q.y+76,w:342,h:250,xmin:-2,xmax:2,ymin:-2,ymax:2,xt:[-2,0,2],yt:[-2,0,2],xlabel:'Mean predicted HI',ylabel:'Mean observed HI',tick:24});ln(a.X(-2),a.Y(-2),a.X(2),a.Y(2),'#87999E',1.8);let cp=[];D.calibration.forEach(v=>{ev(a,v.observed,v.ci,a.X(v.predicted),C.teal);cp.push([a.X(v.predicted),a.Y(v.observed)]);txt(String(v.n),a.X(v.predicted)-22,a.Y(v.observed)-42,44,26,22,false,'center')});pathline(cp,C.teal,2.5);txt('95% participant-bootstrap CI',q.x+63,q.y+416,370,29,22);txt(`Slope ${fmt(D.calstats.slope)}, intercept ${fmt(D.calstats.intercept)}`,q.x+63,q.y+449,380,29,22);
q=box('C','Locked-model residuals',2,0);a=axes({x:q.x+81,y:q.y+76,w:341,h:250,xmin:-3,xmax:3,ymin:-3,ymax:3,xt:[-3,0,3],yt:[-3,0,3],xlabel:'Predicted HI',ylabel:'Observed minus predicted',tick:24});ln(a.X(-3),a.Y(0),a.X(3),a.Y(0),'#87999E',1.8);D.points.ridge.forEach(p=>point(a.X(p.x),a.Y(p.y-p.x),states[p.state],5.5));txt('All outer-fold test predictions',q.x+63,q.y+416,370,29,22);
const models=['persistence','linear','ridge','modules','shrink_ridge','shrink_modules'],titles=['Persistence','Prior-change continuation','Locked Ridge','Ridge + MBX modules','Ridge with shrinkage','Modules with shrinkage'];
models.forEach((key,i)=>{const col=i%3,row=1+Math.floor(i/3),q=box(String.fromCharCode(68+i),titles[i],col,row),perf=D.performance.find(v=>v.model===key);let a=axes({x:q.x+81,y:q.y+103,w:341,h:250,xmin:-4,xmax:4,ymin:-4,ymax:4,xt:[-4,-2,0,2,4],yt:[-4,-2,0,2,4],xlabel:'Predicted next-visit HI',ylabel:'Observed next-visit HI',tick:24});ln(a.X(-4),a.Y(-4),a.X(4),a.Y(4),'#87999E',1.8);D.points[key].forEach(p=>point(a.X(p.x),a.Y(p.y),states[p.state],5.7));txt(`R² ${fmt(perf.r2)}    MAE ${fmt(perf.mae)}`,q.x+73,q.y+51,373,30,24);txt(`MAE CI ${fmt(perf.mae_ci[0])}–${fmt(perf.mae_ci[1])}`,q.x+56,q.y+441,394,29,22,false,'center')});
legend('Low',states[0],235,1683,90);legend('Intermediate',states[1],451,1683,195);legend('High',states[2],788,1683,90);ln(1032,1696,1062,1696,'#87999E',1.8);txt('Identity',1075,1683,170,27,22);
txt('Colors: observed t3 state from outer-training thresholds',40,1728,1360,30,24,false,'center');
txt('Module additions are exploratory. Training-only shrinkage selected lambda = 1 in every fold',35,1769,1370,33,24,false,'center');
S.speakerNotes.textFrame.setText(await fs.readFile(path.join(OUT,'Figure_caption.txt'),'utf8'));
const candidate=path.join(ROOT,'build/s4edit/candidate.pptx');await(await PresentationFile.exportPptx(P)).save(candidate);
const {finalizePresentation}=await import(pathToFileURL('/root/.codex/skills/builtins/presentations/container_tools/artifact_tool_utils.mjs').href);
await finalizePresentation({workspaceDir:ROOT,candidatePath:candidate,finalPath:path.join(OUT,'Supplementary_Fig4.pptx'),pythonExecutable:process.env.CODEX_PRIMARY_RUNTIME_PYTHON,integrityValidatorPath:'/root/.codex/skills/builtins/presentations/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:'/root/.codex/skills/builtins/presentations/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu',`${Math.round(W*scale*9525)},${Math.round(H*scale*9525)}`],explicitTotalSlideCount:1,fontPolicy:{basis:'user_request',families:['Times New Roman']},verifyArtifactToolImport:true,receiptPath:path.join(ROOT,'build/s4edit/validation.json')});console.log('native shapes',serial);
